#version: '3.8'

services:
  app:
    build: .
    image: temesgentesfazgi/final_project:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
    command: gunicorn -b 0.0.0.0:8000 app:app
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
