# Use a specific version of Nginx as the base image
FROM nginx:1.24.0-bullseye

# Copy the Nginx configuration file from your local directory to the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to be accessible from the host
EXPOSE 80
